export const ADD_TO_REAL_CART = "ADD_TO_REAL_CART";

export const ITEM_LOOKUP = "ITEM_LOOKUP";
export const ITEM_LOOKUP_RESP = "ITEM_LOOKUP_RESP";

export const UPDATE_COOKIE = "UPDATE_COOKIE";
export const UPDATE_COOKIE_RESP = "UPDATE_COOKIE_RESP";


export const CART_STATE_LOOKUP = "CART_STATE_LOOKUP";
export const CART_STATE_LOOKUP_RESP = "CART_STATE_LOOKUP_RESP";
